import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/layout/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Load Be Vietnam Pro with all the weights you need
const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  // Include all the weights you plan to use
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  // Include italic styles if needed
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-be-vietnam-pro antialiased `}>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
